import { Chat, Message, Folder, Contact, TeleForgeSettings } from './types';

export const INITIAL_SETTINGS: TeleForgeSettings = {
  experimentalFeatures: true,
  privacyMode: false,
  compactNavigation: false,
  folderFirstWorkflow: true,
  activeTheme: 'teleforge',
  hidePhoneNumber: false,
  disableLinkPreviews: false,
  proxyEnabled: true,
  proxyType: 'MTProxy',
  proxyServer: 'proxy.teleforge.org:443',
  proxyPing: 28,
  developerDiagnostics: false,
  bubbleStyle: 'modern',
};

export const INITIAL_FOLDERS: Folder[] = [
  { id: 'all', name: 'All Chats', icon: '💬', color: '#5EEAD4', isDefault: true, filterTypes: ['direct', 'group', 'channel', 'bot'] },
  { id: 'work', name: 'Work & Projects', icon: '💼', color: '#60A5FA', filterTypes: ['group', 'direct'] },
  { id: 'channels', name: 'Channels & News', icon: '📢', color: '#F472B6', filterTypes: ['channel'] },
  { id: 'bots', name: 'Bots & Tools', icon: '🤖', color: '#A78BFA', filterTypes: ['bot'] },
  { id: 'crypto', name: 'Crypto & Alpha', icon: '💎', color: '#FBBF24', filterTypes: ['channel', 'group'] },
];

export const INITIAL_CHATS: Chat[] = [
  {
    id: 'c1',
    title: 'TeleForge Announcements',
    type: 'channel',
    avatar: 'TF',
    avatarColor: 'from-teal-500 to-emerald-600',
    lastMessage: 'v3.0.4 update rolled out: Power Folders, Theme Studio and native speed optimizations.',
    timestamp: '19:42',
    unreadCount: 2,
    isPinned: true,
    isMuted: false,
    verified: true,
    folderIds: ['all', 'channels'],
    membersCount: 48920,
  },
  {
    id: 'c2',
    title: 'Pavel Durov',
    type: 'direct',
    avatar: 'PD',
    avatarColor: 'from-blue-600 to-indigo-700',
    lastMessage: 'Good work on the Telegram client architecture. The custom tab layout feels very fluid.',
    timestamp: '18:15',
    unreadCount: 1,
    isPinned: true,
    isMuted: false,
    isOnline: true,
    verified: true,
    folderIds: ['all', 'work'],
  },
  {
    id: 'c3',
    title: 'Rust Core Devs',
    type: 'group',
    avatar: '🦀',
    avatarColor: 'from-amber-600 to-orange-700',
    lastMessage: 'Alexander: The memory footprint of the new parser dropped by 34% with zero allocs.',
    lastMessageSender: 'Alexander',
    timestamp: '17:50',
    unreadCount: 14,
    isPinned: false,
    isMuted: true,
    folderIds: ['all', 'work'],
    membersCount: 1240,
  },
  {
    id: 'c4',
    title: 'TeleForge Assistant Bot',
    type: 'bot',
    avatar: '🤖',
    avatarColor: 'from-cyan-500 to-blue-600',
    lastMessage: 'Proxy ping: 28ms via MTProxy Singapore node. All circuits healthy.',
    timestamp: '16:22',
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    verified: true,
    folderIds: ['all', 'bots'],
  },
  {
    id: 'c5',
    title: 'Elena Rostova',
    type: 'direct',
    avatar: 'ER',
    avatarColor: 'from-purple-500 to-pink-600',
    lastMessage: 'Did you review the UI specifications for the Theme Studio color picker?',
    timestamp: '14:03',
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isOnline: true,
    folderIds: ['all', 'work'],
  },
  {
    id: 'c6',
    title: 'Crypto Alpha Radar',
    type: 'channel',
    avatar: '📈',
    avatarColor: 'from-emerald-600 to-teal-800',
    lastMessage: 'BTC breaks past critical resistance. Volume spike across major spot desks.',
    timestamp: '12:11',
    unreadCount: 5,
    isPinned: false,
    isMuted: true,
    folderIds: ['all', 'channels', 'crypto'],
    membersCount: 89400,
  },
  {
    id: 'c7',
    title: 'Marcus Brody',
    type: 'direct',
    avatar: 'MB',
    avatarColor: 'from-slate-600 to-zinc-700',
    lastMessage: 'Sent you the decrypted trace file.',
    timestamp: 'Yesterday',
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isOnline: false,
    folderIds: ['all'],
  },
  {
    id: 'c8',
    title: 'AI Studio Engineering',
    type: 'group',
    avatar: '⚡',
    avatarColor: 'from-violet-600 to-purple-800',
    lastMessage: 'Deployment build completed with green status across all nodes.',
    lastMessageSender: 'CI/CD Bot',
    timestamp: 'Sep 12',
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    folderIds: ['all', 'work'],
    membersCount: 312,
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  c1: [
    {
      id: 'm1-1',
      chatId: 'c1',
      sender: 'them',
      senderName: 'TeleForge Channel',
      text: '🚀 Welcome to TeleForge! A dedicated client built for power users demanding precision controls, customizable tabs, and zero clutter.',
      timestamp: '18:00',
      status: 'read',
      reactions: [{ emoji: '🔥', count: 184 }, { emoji: '⚡', count: 96 }],
    },
    {
      id: 'm1-2',
      chatId: 'c1',
      sender: 'them',
      senderName: 'TeleForge Channel',
      text: 'v3.0.4 update rolled out: Power Folders, Theme Studio and native speed optimizations.',
      timestamp: '19:42',
      status: 'read',
      reactions: [{ emoji: '❤️', count: 320 }, { emoji: '🚀', count: 142 }],
    },
  ],
  c2: [
    {
      id: 'm2-1',
      chatId: 'c2',
      sender: 'them',
      senderName: 'Pavel Durov',
      text: 'Hey! Saw your recent patches on the Android Telegram client.',
      timestamp: '18:10',
      status: 'read',
    },
    {
      id: 'm2-2',
      chatId: 'c2',
      sender: 'me',
      text: 'Thank you Pavel! We focused on keeping upstream compatibility while giving power users the Power Folders and Theme Studio they wanted.',
      timestamp: '18:12',
      status: 'read',
    },
    {
      id: 'm2-3',
      chatId: 'c2',
      sender: 'them',
      senderName: 'Pavel Durov',
      text: 'Good work on the Telegram client architecture. The custom tab layout feels very fluid.',
      timestamp: '18:15',
      status: 'read',
      reactions: [{ emoji: '👍', count: 1 }],
    },
  ],
  c4: [
    {
      id: 'm4-1',
      chatId: 'c4',
      sender: 'them',
      senderName: 'TeleForge Bot',
      text: 'Hello! I am your TeleForge assistant. Commands:\n/proxy - Check MTProxy status\n/folders - Power Folder analytics\n/stats - Client memory & throughput stats',
      timestamp: '16:20',
      status: 'read',
    },
    {
      id: 'm4-2',
      chatId: 'c4',
      sender: 'me',
      text: '/proxy',
      timestamp: '16:21',
      status: 'read',
    },
    {
      id: 'm4-3',
      chatId: 'c4',
      sender: 'them',
      senderName: 'TeleForge Bot',
      text: 'Proxy ping: 28ms via MTProxy Singapore node. All circuits healthy.',
      timestamp: '16:22',
      status: 'read',
    },
  ],
};

export const INITIAL_CONTACTS: Contact[] = [
  { id: 'u1', name: 'Alexander Vance', username: '@avance', phone: '+1 415 555 0192', status: 'Building the next generation UX', isOnline: true, avatarColor: 'bg-emerald-600' },
  { id: 'u2', name: 'Elena Rostova', username: '@erostova', phone: '+44 7911 123456', status: 'Offline for dinner', isOnline: true, avatarColor: 'bg-indigo-600' },
  { id: 'u3', name: 'Marcus Brody', username: '@mbrody', phone: '+1 650 555 7843', status: 'At cryptography summit', isOnline: false, avatarColor: 'bg-amber-600' },
  { id: 'u4', name: 'Pavel Durov', username: '@durov', phone: 'Hidden by Privacy Mode', status: 'TeleForge power user', isOnline: true, avatarColor: 'bg-blue-600' },
  { id: 'u5', name: 'Sarah Jenkins', username: '@sjenkins', phone: '+1 212 555 4912', status: 'Focusing on code', isOnline: false, avatarColor: 'bg-rose-600' },
  { id: 'u6', name: 'Viktor Krum', username: '@vkrum', phone: '+49 30 901820', status: 'Available', isOnline: false, avatarColor: 'bg-purple-600' },
];
